/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Point;
import java.awt.Toolkit;
import org.dom4j.DocumentException;
import utils.Utils;

/**
 *
 * @author sala308b
 */
public class AppMain extends javax.swing.JFrame {

    public AppMain() {
        initComponents();
        super.setExtendedState(MAXIMIZED_BOTH);//inicia maximizado.
        super.setIconImage(Toolkit.getDefaultToolkit()
                     .getImage("src/imagens/app_icon.jpg"));
        desativarMenus();

//      controller.ClientesController clienteController = new controller.ClientesController();
//      clienteController.incluir();
      
//      dao.ClienteDAO dao = new dao.ClienteDAO();
//      java.util.ArrayList<Object> listaClientes = dao.listar();
//      listaClientes.stream().map((o) -> (model.Cliente) o).forEach((cli) -> {
//          System.out.println("Cliente: " + cli.getNome() );
//        });
//      System.exit(0);
    }

    /**
     * Exibier o formulário frente de loja centralizado;
     */
    public void showFormFrenteLoja() {
        FormFrenteLoja frenteLoja = new FormFrenteLoja();
        desktopPane.add(frenteLoja);
        frenteLoja.setVisible(true);
        Point p = Utils.centralizarFormInterno(frenteLoja, desktopPane);
        frenteLoja.setLocation(p);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuAtivarMenus = new javax.swing.JMenu();
        mnuLogin = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuFrenteLoja = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuFornecedores = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuPrecos = new javax.swing.JMenuItem();
        mnuEstoque = new javax.swing.JMenuItem();
        mnuComanda = new javax.swing.JMenuItem();
        mnuFerrmentas = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Janela Principal");

        mnuAtivarMenus.setText("Sistema");

        mnuLogin.setText("Login");
        mnuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoginActionPerformed(evt);
            }
        });
        mnuAtivarMenus.add(mnuLogin);
        mnuAtivarMenus.add(jSeparator1);

        mnuFrenteLoja.setText("Frente de Loja");
        mnuFrenteLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFrenteLojaActionPerformed(evt);
            }
        });
        mnuAtivarMenus.add(mnuFrenteLoja);

        jMenuItem1.setText("Ativar Menus");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAtivarMenus.add(jMenuItem1);
        mnuAtivarMenus.add(jSeparator2);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuAtivarMenus.add(mnuSair);

        menuBar.add(mnuAtivarMenus);

        mnuCadastros.setText("Cadastros");

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuClientes);

        mnuFornecedores.setText("Fornecedores");
        mnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuFornecedores);

        mnuProdutos.setText("Produtos");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuProdutos);

        mnuUsuarios.setText("Usuários");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuUsuarios);

        menuBar.add(mnuCadastros);

        mnuConsultas.setText("Consultas");

        mnuPrecos.setText("Preço");
        mnuPrecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrecosActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuPrecos);

        mnuEstoque.setText("Estoque");
        mnuEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEstoqueActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuEstoque);

        mnuComanda.setText("Comanda");
        mnuComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComandaActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuComanda);

        menuBar.add(mnuConsultas);

        mnuFerrmentas.setText("Ferramentas");

        jMenuItem10.setText("Backup");
        mnuFerrmentas.add(jMenuItem10);

        jMenuItem11.setText("Restore");
        mnuFerrmentas.add(jMenuItem11);

        menuBar.add(mnuFerrmentas);

        mnuRelatorios.setText("Relatórios");

        jMenu6.setText("Vendas");

        jMenuItem12.setText("Diárias");
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Semanal");
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("Mensal");
        jMenu6.add(jMenuItem14);

        mnuRelatorios.add(jMenu6);

        menuBar.add(mnuRelatorios);

        jMenu7.setText("Ajuda");

        jMenuItem15.setText("Sobre");
        jMenu7.add(jMenuItem15);

        jMenuItem16.setText("Tópicos");
        jMenu7.add(jMenuItem16);

        menuBar.add(jMenu7);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoginActionPerformed
        // TODO add your handling code here:

        showLoginForm();

        if (Utils.isAuth()) {
            ativarMenus();
        }

    }//GEN-LAST:event_mnuLoginActionPerformed

    private void showLoginForm() {
        FormLogin formLogin = new FormLogin();
        desktopPane.add(formLogin);

        int width, height;
        width = (desktopPane.getWidth() - formLogin.getWidth()) / 2;
        height = (desktopPane.getHeight() - formLogin.getHeight()) / 2;

        formLogin.setLocation(width, height);

        formLogin.setVisible(true);

    }
    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);//Fechar a aplicação...
    }//GEN-LAST:event_mnuSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (Utils.isAuth()) {
            ativarMenus();
            //showFormFrenteLoja();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        FormClientes formClientes = new FormClientes();
        desktopPane.add(formClientes);

        int width, height;
        width = (desktopPane.getWidth() - formClientes.getWidth()) / 2;
        height = (desktopPane.getHeight() - formClientes.getHeight()) / 2;

        formClientes.setLocation(width, height);

        formClientes.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFornecedoresActionPerformed
        // TODO add your handling code here:
        FormFornecedores formFornecedores = new FormFornecedores();
        desktopPane.add(formFornecedores);

        int width, height;
        width = (desktopPane.getWidth() - formFornecedores.getWidth()) / 2;
        height = (desktopPane.getHeight() - formFornecedores.getHeight()) / 2;

        formFornecedores.setLocation(width, height);

        formFornecedores.setVisible(true);
    }//GEN-LAST:event_mnuFornecedoresActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        // TODO add your handling code here:
        FormProdutos formProdutos = new FormProdutos();
        desktopPane.add(formProdutos);

        int width, height;
        width = (desktopPane.getWidth() - formProdutos.getWidth()) / 2;
        height = (desktopPane.getHeight() - formProdutos.getHeight()) / 2;

        formProdutos.setLocation(width, height);

        formProdutos.setVisible(true);
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        // TODO add your handling code here:
        FormUsuarios formUsuarios = new FormUsuarios();
        desktopPane.add(formUsuarios);

        int width, height;
        width = (desktopPane.getWidth() - formUsuarios.getWidth()) / 2;
        height = (desktopPane.getHeight() - formUsuarios.getHeight()) / 2;

        formUsuarios.setLocation(width, height);

        formUsuarios.setVisible(true);
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    private void mnuPrecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrecosActionPerformed
        // TODO add your handling code here:
        FormPrecos formPrecos = new FormPrecos();
        desktopPane.add(formPrecos);

        int width, height;
        width = (desktopPane.getWidth() - formPrecos.getWidth()) / 2;
        height = (desktopPane.getHeight() - formPrecos.getHeight()) / 2;

        formPrecos.setLocation(width, height);

        formPrecos.setVisible(true);
    }//GEN-LAST:event_mnuPrecosActionPerformed

    private void mnuEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEstoqueActionPerformed
        // TODO add your handling code here:
        FormEstoque formEstoque = new FormEstoque();
        desktopPane.add(formEstoque);

        int width, height;
        width = (desktopPane.getWidth() - formEstoque.getWidth()) / 2;
        height = (desktopPane.getHeight() - formEstoque.getHeight()) / 2;

        formEstoque.setLocation(width, height);

        formEstoque.setVisible(true);
    }//GEN-LAST:event_mnuEstoqueActionPerformed

    private void mnuComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComandaActionPerformed
        // TODO add your handling code here:
        FormComanda formComanda = new FormComanda();
        desktopPane.add(formComanda);

        int width, height;
        width = (desktopPane.getWidth() - formComanda.getWidth()) / 2;
        height = (desktopPane.getHeight() - formComanda.getHeight()) / 2;

        formComanda.setLocation(width, height);

        formComanda.setVisible(true);
    }//GEN-LAST:event_mnuComandaActionPerformed

    private void mnuFrenteLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFrenteLojaActionPerformed
        showFormFrenteLoja();
    }//GEN-LAST:event_mnuFrenteLojaActionPerformed

    private void ativarMenus() {

        mnuCadastros.setEnabled(true);
        mnuFrenteLoja.setEnabled(true);
        mnuConsultas.setEnabled(true);
        mnuFerrmentas.setEnabled(true);
        mnuLogin.setEnabled(false);
        mnuRelatorios.setEnabled(true);

        menuBar.updateUI();

    }

    private void desativarMenus() {
        mnuCadastros.setEnabled(false);
        mnuConsultas.setEnabled(false);
        mnuFerrmentas.setEnabled(false);
        mnuFrenteLoja.setEnabled(false);
        mnuLogin.setEnabled(true);
        mnuRelatorios.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMain().setVisible(true);
            }
        });
        
        
    }

    
    public void testarConexao() throws DocumentException{
        dao.Conexao conexao = new dao.Conexao();
        com.mysql.jdbc.MySQLConnection con = conexao.getCon();
        String servidor = con.getServerVersion();
        String host = con.getHost();
              
        System.out.println("Servidor: " + servidor);
        System.out.println("Host: " + host);
        
        conexao.Fechar();
        System.exit(0);        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAtivarMenus;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuComanda;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuItem mnuEstoque;
    private javax.swing.JMenu mnuFerrmentas;
    private javax.swing.JMenuItem mnuFornecedores;
    private javax.swing.JMenuItem mnuFrenteLoja;
    private javax.swing.JMenuItem mnuLogin;
    private javax.swing.JMenuItem mnuPrecos;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuUsuarios;
    // End of variables declaration//GEN-END:variables

}
